#name: Deploy to S3
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#
#      - name: Install dependencies and build
#        run: |
#          npm install
#          npm run build
#
#      - name: Deploy to S3
#        uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --delete
#        env:
#          AWS_S3_BUCKET: jonathan-kwok-portfolio
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: eu-west-2
#          SOURCE_DIR: ./build
#
#permissions:
#  contents: read